### Rota Clientes 

###
GET http://localhost:3000/clients


###
POST http://localhost:3000/newClient
Content-Type: application/json

{
    "fullName": "Pedro Pandorim",
    "cpf": "13325928454",
    "tel": "24141825687",
    "active": "sim",
    "cep": "44054362",
    "address": "Gentio do Ouro",
    "district": "Parque Ipê",
    "city": "Feira de Santana",
    "state": "BA"
}

###
DELETE http://localhost:3000/cliente/64680f92271438b6a2a09b59


### Rota Categoria

###
POST http://localhost:3000/createCategory
Content-Type: application/json

{
    "name": "Brinquedo"
}

###
GET http://localhost:3000/categoryList

### Rota Pets

###
GET http://localhost:3000/pets

###
PUT  http://localhost:3000/updatePet/6477c76672b62f50d480d11e
Content-Type: application/json

{
    "petPicture": "asdasd",
    "name": "José Messia",
    "race": "Pé Duro",
    "size": "Médio",
    "age": 8,
    "weight": 10.3,
    "sex": "Macho",
    "owner": "646fdb15f7ffc8723b41ac9d"
}

###

DELETE http://localhost:3000/deletePet/64772fa255acbf3db1c428d3


### Rota Produto

POST http://localhost:3000/newProduct
Content-Type: application/json

{
    "name": "Ração Premiumn",
    "category": "6470a026ccf53739a6f6a099",
    "stock": 2222,
    "price": 666
}

###
GET http://localhost:3000/services


### Rota Usuário
POST http://localhost:3000/newService/647df68b338f9f4537281c73/646fdb15f7ffc8723b41ac9d
Content-Type: application/json

{
    "bath": true,
    "shave": true,
    "nails": false,
    "delivery": true
}

###
DELETE http://localhost:3000/deleteService/647e66aa003f2c05ab58227b